spring.datasource.url=jdbc:mysql://localhost:3306/db_sports?useSSL=false&&allowPublicKeyRetrieval=true&&serverTimezone=Asia/Ho_Chi_Minh
spring.datasource.username = root
spring.datasource.password = 184703